name: CI

on: [ push, pull_request ]

jobs:
    black-box-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                redis-version: [ "2.8", "3.0", "4.0", "5.0", "6.0", "7.0" ]
            fail-fast: false
        steps:
            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Setup Golang with cache
                uses: magnetikonline/action-golang-cache@v3
                with:
                    go-version-file: go.mod

            -   name: clone and make redis
                run: |
                    sudo apt-get install git
                    git clone https://github.com/redis/redis
                    cd redis
                    git checkout ${{ matrix.redis-version }}
                    make -j
                    mkdir bin
                    cp src/redis-server bin/redis-server
                    echo "$GITHUB_WORKSPACE/redis/bin" >> $GITHUB_PATH
                    ls $GITHUB_WORKSPACE
                    cat $GITHUB_PATH
                    cat /etc/ld.so.conf
            
            -   name: clone and make TairString Module
                if:  contains( '5.0, 6.0, 7.0', matrix.redis-version)
                run: |
                    echo "moduleSuppported=true" >> "$GITHUB_ENV"
                    echo "${{ env.moduleSuppported }}"
                    cd $GITHUB_WORKSPACE
                    git clone https://github.com/tair-opensource/TairString.git
                    cd TairString 
                    mkdir build 
                    cd build 
                    cmake ../ && make -j
                    sudo cp $GITHUB_WORKSPACE/TairString/lib/tairstring_module.so /lib
                    
                    
                    ls $GITHUB_WORKSPACE
                    echo "aaaaaaa"
                    cat $GITHUB_PATH
                    echo "bbbbbbbbbb"
                    less /etc/ld.so.conf

            -   name: clone and make TairHash Module
                if:  contains( '5.0, 6.0, 7.0', matrix.redis-version)
                run: |
                    cd $GITHUB_WORKSPACE
                    git clone https://github.com/tair-opensource/TairHash.git
                    cd TairHash 
                    mkdir build 
                    cd build 
                    cmake ../ && make -j
                    sudo cp $GITHUB_WORKSPACE/TairHash/lib/tairhash_module.so /lib
        
                    
                    ls $GITHUB_WORKSPACE
                    echo "aaaaaaa"
                    cat $GITHUB_PATH
                    echo "bbbbbbbbbb"
                    less /etc/ld.so.conf

            -   name: clone and make TairZset Module
                if:  contains( '5.0, 6.0, 7.0', matrix.redis-version)
                run: |
                    cd $GITHUB_WORKSPACE
                    git clone https://github.com/tair-opensource/TairZset.git
                    cd TairZset 
                    mkdir build 
                    cd build 
                    cmake ../ && make -j
                    sudo cp $GITHUB_WORKSPACE/TairZset/lib/tairzset_module.so /lib
        
                    
                    ls $GITHUB_WORKSPACE
                    echo "aaaaaaa"
                    cat $GITHUB_PATH
                    echo "bbbbbbbbbb"
                    less /etc/ld.so.conf


            -   name: Setup Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.11'

            -   name: make redis-shake
                run: |
                    sh build.sh 


            -   name: test with module supported
                if:  contains( '5.0, 6.0, 7.0', matrix.redis-version)
                run: |
                    echo "${{ env.moduleSupported }}"
                    echo "moduleSupported=true" >> "$GITHUB_ENV"
                    echo "${{ env.moduleSupported }}"
                    pip3 install -r tests/requirements.txt
                    sh test.sh
                
            -   name: test withnot moduele supported
                if:  contains( '2.8, 3.0, 4.0', matrix.redis-version)
                run: |
                    echo "${{ env.moduleSupported }}"
                    echo "moduleSupported=false" >> "$GITHUB_ENV"
                    echo "${{ env.moduleSupported }}"
                    pip3 install -r tests/requirements.txt
                    sh test.sh

